export type SearchResult = {
    id: string;
    title: string;
    category: string;
    hot?: boolean;
    generalAgent?: boolean;
    image: string;
    artists?: string;
    date?: string;
    platform: string;
    city?: string;
    address?: string;
    lng?: number;
    lat?: number;
    rating?: number;
    priceRange?: string;
    score: number;
    wantNum?: string;
    wantNumSuffix?: string;
    wantDesc?: string;
};
